services:
    mongo:
        image: mongo:7.0-rc
        container_name: mongo
        restart: always
        ports:
        - 27017:27017
        volumes:
        - db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${AMBULANCE_API_MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${AMBULANCE_API_MONGODB_PASSWORD}
    mongo_express:
#        image: mendhak/http-https-echo
        image: mongo-express
        container_name: mongo_express
        restart: always
        ports:
#        - 8081:8080
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME:  ${AMBULANCE_API_MONGODB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${AMBULANCE_API_MONGODB_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongo
#            ME_CONFIG_MONGODB_URL: mongodb://root:neUhaDnes@mongo:27017/
            ME_CONFIG_BASICAUTH_USERNAME: 'meme'
            ME_CONFIG_BASICAUTH_PASSWORD: 'meme'
        depends_on:
        - mongo
        # links:
        # - mongo_db
volumes:
    db_data: {}